# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'photo_up' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for photo_up
  pod 'Firebase/Core'
  pod 'Firebase/Storage', '~> 5.15.0'
  pod 'Firebase/Database', '~> 5.15.0'

  target 'photo_up-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'photo_upTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

# target 'photo_up-tvOS' do
#   # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#   # use_frameworks!
# 
#   # Pods for photo_up-tvOS
# 
#   target 'photo_up-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end
# 
# end
